// lib/src/repositories/auth_repository.dart

import 'package:dairynote_client/dairynote_client.dart';
import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';

part 'auth_repository.g.dart'; // This will be generated by build_runner

@RestApi()
abstract class AuthRepository {
  factory AuthRepository(Dio dio, {String baseUrl}) = _AuthRepository;

  @POST('/auth/login/phone')
  Future<AuthenticationResponse> loginWithPhone(
    @Field() String phone,
   {
     @Field() String? fcmToken,
   }
  );

  @POST('/auth/login/phone-email')
  Future<AuthenticationResponse> loginWithPhoneEmail(
    @Field() String accessToken, {
    @Field() String? fcmToken,
  });

  @GET('/auth/sync/{id}')
  Future<UserInfo?> fetchSync(@Path('id') String id);

  @POST('/auth/logout')
  Future<void> logout(); // userId is handled by token on server-side
}
